
-- Add 'sinif' and 'tahsilat_durumu' to leads table
ALTER TABLE leads ADD COLUMN IF NOT EXISTS sinif TEXT DEFAULT 'Normal';
ALTER TABLE leads ADD COLUMN IF NOT EXISTS tahsilat_durumu TEXT;

-- Create collection_notes table
CREATE TABLE IF NOT EXISTS collection_notes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lead_id UUID REFERENCES leads(id) ON DELETE CASCADE,
    user_email TEXT,
    note TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Add index for performance
CREATE INDEX IF NOT EXISTS idx_leads_sinif ON leads(sinif);
CREATE INDEX IF NOT EXISTS idx_collection_notes_lead_id ON collection_notes(lead_id);
