
-- 1. Add Columns to Leads Table
ALTER TABLE leads ADD COLUMN IF NOT EXISTS sinif TEXT DEFAULT 'Normal';
ALTER TABLE leads ADD COLUMN IF NOT EXISTS tahsilat_durumu TEXT;

-- 2. Create Collection Notes Table
CREATE TABLE IF NOT EXISTS collection_notes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lead_id UUID REFERENCES leads(id) ON DELETE CASCADE,
    user_email TEXT,
    note TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Create Settings Tables
CREATE TABLE IF NOT EXISTS customer_classes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    label TEXT NOT NULL UNIQUE,
    color TEXT DEFAULT 'gray',
    sort_order INT DEFAULT 0,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS collection_statuses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    label TEXT NOT NULL UNIQUE,
    color TEXT DEFAULT 'blue',
    sort_order INT DEFAULT 0,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Seed Initial Data
INSERT INTO customer_classes (label, color, sort_order)
SELECT 'Normal', 'gray', 1 WHERE NOT EXISTS (SELECT 1 FROM customer_classes WHERE label = 'Normal');
INSERT INTO customer_classes (label, color, sort_order)
SELECT 'VIP', 'amber', 2 WHERE NOT EXISTS (SELECT 1 FROM customer_classes WHERE label = 'VIP');
INSERT INTO customer_classes (label, color, sort_order)
SELECT 'Gecikme', 'red', 3 WHERE NOT EXISTS (SELECT 1 FROM customer_classes WHERE label = 'Gecikme');

INSERT INTO collection_statuses (label, color, sort_order)
SELECT 'Ulaşılamadı', 'red', 1 WHERE NOT EXISTS (SELECT 1 FROM collection_statuses WHERE label = 'Ulaşılamadı');
INSERT INTO collection_statuses (label, color, sort_order)
SELECT 'Ödeme Sözü Alındı', 'green', 2 WHERE NOT EXISTS (SELECT 1 FROM collection_statuses WHERE label = 'Ödeme Sözü Alındı');
INSERT INTO collection_statuses (label, color, sort_order)
SELECT 'Avukata Sevk', 'orange', 3 WHERE NOT EXISTS (SELECT 1 FROM collection_statuses WHERE label = 'Avukata Sevk');
