
import { NextRequest, NextResponse } from 'next/server';
import { supabaseAdmin } from '@/lib/supabase';

export const dynamic = 'force-dynamic';

export async function GET(req: NextRequest) {
    try {
        // Raw SQL for migration
        const sql = `
            -- Add 'sinif' and 'tahsilat_durumu' to leads table
            ALTER TABLE leads ADD COLUMN IF NOT EXISTS sinif TEXT DEFAULT 'Normal';
            ALTER TABLE leads ADD COLUMN IF NOT EXISTS tahsilat_durumu TEXT;

            -- Create collection_notes table
            CREATE TABLE IF NOT EXISTS collection_notes (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                lead_id UUID REFERENCES leads(id) ON DELETE CASCADE,
                user_email TEXT,
                note TEXT,
                created_at TIMESTAMPTZ DEFAULT NOW()
            );

            -- Create customer_classes table
            CREATE TABLE IF NOT EXISTS customer_classes (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                label TEXT NOT NULL UNIQUE,
                color TEXT DEFAULT 'gray',
                sort_order INT DEFAULT 0,
                is_active BOOLEAN DEFAULT TRUE,
                created_at TIMESTAMPTZ DEFAULT NOW()
            );

            -- Create collection_statuses table
            CREATE TABLE IF NOT EXISTS collection_statuses (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                label TEXT NOT NULL UNIQUE,
                color TEXT DEFAULT 'blue',
                sort_order INT DEFAULT 0,
                is_active BOOLEAN DEFAULT TRUE,
                created_at TIMESTAMPTZ DEFAULT NOW()
            );

            -- Seed initial data if empty
            INSERT INTO customer_classes (label, color, sort_order)
            SELECT 'Normal', 'gray', 1 WHERE NOT EXISTS (SELECT 1 FROM customer_classes WHERE label = 'Normal');
            INSERT INTO customer_classes (label, color, sort_order)
            SELECT 'VIP', 'amber', 2 WHERE NOT EXISTS (SELECT 1 FROM customer_classes WHERE label = 'VIP');
            INSERT INTO customer_classes (label, color, sort_order)
            SELECT 'Gecikme', 'red', 3 WHERE NOT EXISTS (SELECT 1 FROM customer_classes WHERE label = 'Gecikme');

            INSERT INTO collection_statuses (label, color, sort_order)
            SELECT 'Ulaşılamadı', 'red', 1 WHERE NOT EXISTS (SELECT 1 FROM collection_statuses WHERE label = 'Ulaşılamadı');
            INSERT INTO collection_statuses (label, color, sort_order)
            SELECT 'Ödeme Sözü Alındı', 'green', 2 WHERE NOT EXISTS (SELECT 1 FROM collection_statuses WHERE label = 'Ödeme Sözü Alındı');
             INSERT INTO collection_statuses (label, color, sort_order)
            SELECT 'Avukata Sevk', 'orange', 3 WHERE NOT EXISTS (SELECT 1 FROM collection_statuses WHERE label = 'Avukata Sevk');
            INSERT INTO collection_statuses (label, color, sort_order)
            SELECT 'Avukata Hazırlık Aşaması', 'orange', 4 WHERE NOT EXISTS (SELECT 1 FROM collection_statuses WHERE label = 'Avukata Hazırlık Aşaması');

            -- Add index for performance
            CREATE INDEX IF NOT EXISTS idx_leads_sinif ON leads(sinif);
            CREATE INDEX IF NOT EXISTS idx_collection_notes_lead_id ON collection_notes(lead_id);
        `;

        const { error } = await supabaseAdmin.rpc('exec_sql', { sql_query: sql });

        if (error) {
            console.error('RPC Error:', error);
            // Fallback: If exec_sql doesn't exist, we return error. 
            // In a real scenario, we might try to create the function first, but we can't create function without SQL access.
            return NextResponse.json({ success: false, error: error.message, hint: "Make sure exec_sql RPC function exists." });
        }

        return NextResponse.json({ success: true, message: 'Migration executed successfully' });

    } catch (e: any) {
        return NextResponse.json({ success: false, error: e.message });
    }
}
